### ISSUE TITLE
open on startup not working

### ISSUE THREAD

**Issue by davidhu2000** [manosim/gitify#313] opened 2017-07-25 17:11 UTC
Gitify never loads on startup despite having the option checked.

**Comment by AriLFrankel** [comment] 2018-03-07 15:50
@davidhu2000 I am experiencing the same issue

What system / version of Gitify are you using? I am on MacOS High Sierra with Gitify 2.0.2

**Comment by JakeSidSmith** [comment] 2018-03-07 16:00
@AriLFrankel can you try toggling the option off and on again, and then restart?

**Comment by AriLFrankel** [comment] 2018-03-07 17:01
@JakeSidSmith That did not work for me unfortunately.

**Comment by AriLFrankel** [comment] 2018-03-07 17:10
@JakeSidSmith I think I see what happened, and it was not an issue with Gitify.

I will document my solution here in case this happens for other folks.

Navigate to System Preferences => Users and Groups => yourself => Login Items

In the row containing Gitify there was a yellow triangle warning in the right most column. This can indicate that the application has been moved since it was added. 

I highlighted that row and removed it from the login items with - button.
I toggled the `open on startup` setting in Gitify and the row reappeared without the yellow triangle.

**Comment by JakeSidSmith** [comment] 2018-03-13 14:04
Ah, had you manually installed a new version? @AriLFrankel

**Comment by AriLFrankel** [comment] 2018-03-13 14:08
Sorry @JakeSidSmith I don't recall

**Comment by JakeSidSmith** [comment] 2018-03-13 14:12
<img width="403" alt="screen shot 2018-03-13 at 14 10 40" src="https://user-images.githubusercontent.com/5850625/37346846-5e5c88a2-26c8-11e8-84e8-2f01f7f15627.png">

Seems I have the same thing for a dev build I was running a while ago.

I can only assume that a new version was manually installed, but that doesn't mean there is not an issue with Gitify here.

If possible, it'd be good to make sure new manually installed versions updated the Login Items.

**Comment by AriLFrankel** [comment] 2018-06-16 08:36
I was able to reproduce this behavior by manually installing different versions of the app.

I do find though that I need to toggle off/on the Open at Startup option to get Gitify added to the Login Items.

**Comment by manosim** [comment] 2020-02-10 03:44
Hi everyone, closing this one as it shouldn't be an issue but let me know if that's the case and I'm happy to reopen it. 😃

**Closed by manosim** 2020-02-10 03:44 UTC
