### ISSUE TITLE
GitHub no longer supports your web browser

### ISSUE THREAD

**Issue by blakekrammes** [manosim/gitify#360] opened 2019-08-14 13:12 UTC
It won't let me authenticate with GitHub because it says it no longer supports IE, which I don't have installed.

<img width="1036" alt="Screen Shot 2019-08-14 at 8 10 15 AM" src="https://user-images.githubusercontent.com/49688912/63023592-0bc8d500-be6b-11e9-9bf1-46abb061f66f.png">

**Comment by JakeSidSmith** [comment] 2019-08-14 13:17
Duplicate of #355

There are some work-around in that thread.

**Closed by JakeSidSmith** 2019-08-14 13:17 UTC
