### ISSUE TITLE
Mark as read when clicking notification

### ISSUE THREAD

**Issue by aparajita** [manosim/gitify#412] opened 2020-06-02 15:01 UTC
Gitify 3.0.5
macOS 10.15.5

When clicking a notification, it correctly takes me to the relevant place in github, but the corresponding item in Gitify is not marked as read.

**Comment by JakeSidSmith** [comment] 2020-06-03 08:27
I've just upgraded and it appears to work fine for me. Does the notifications still appear after you hit the refresh icon?

**Comment by aparajita** [comment] 2020-06-03 13:48
The point is I shouldn't have to manually refresh. 😁

**Comment by codebytere** [comment] 2020-06-19 16:31
hmm - i'm on the same version and i've not had to manually refresh 🤔 do you have a gif or something demonstrating the behavior?

**Comment by aparajita** [comment] 2020-06-19 16:34
Leave a comment again so I can record.

**Comment by JakeSidSmith** [comment] 2020-06-22 10:03
> The point is I shouldn't have to manually refresh. 😁

The reason I asked was to make sure that they are actually marked as read, which they are, there is not a bug.

Gitify polls the notifications every 60 seconds. So they will disappear from the app within a minute at most.

Is what you are asking for optimistic updates?

**Comment by aparajita** [comment] 2020-06-22 10:09
Yes, I see it eventually goes away. But I think you can know when the notification is clicked, in which case you might as well remove that item from the list. From a UX perspective it is expected.

**Closed** 2023-01-30 15:50 UTC
