### ISSUE TITLE
Bug: Can't open notification from a Discussion page

### ISSUE THREAD

**Issue by phoenixeliot** [manosim/gitify#506] opened 2021-07-07 18:15 UTC
I had a notification of a reply here: https://github.com/prisma/prisma/discussions/4185

Clicking the notification in the Gitify app did nothing. I assume this is because Discussions are a new feature and aren't expected by the app, yet.

**Comment by codebytere** [comment] 2021-07-13 19:17
Duplicate of https://github.com/manosim/gitify/issues/501

**Closed by codebytere** 2021-07-13 19:17 UTC
