### ISSUE TITLE
Feature request: Add an option to make it behave like a menubar app again

### ISSUE THREAD

**Issue by kaicataldo** [manosim/gitify#314] opened 2017-07-26 14:29 UTC
First of all, thanks for this great app - it's made my open source work much easier (and my email inbox lighter)!

Would you be amenable to adding an option (defaulting to off) that would make it more menubar-like again? I really liked how it used to always open in the current workspace and how it would appear right below the tray icon. 

I'd be happy to make a PR, if this is something the maintainer would be okay with :)

**Comment by callumacrae** [comment] 2017-07-27 13:22
yes, please! i've had to stop using gitify as it hinders my workflow more than it helps it, now :(

as it doesn't close after you click on a notification, it's displaying on the wrong monitor, or in the wrong space, so the next time I use it, it changes spaces or opens on the wrong display, and it takes a second to find it. it's much quicker to just open github and click on notifications since the last update.

**Comment by OGKevin** [comment] 2017-08-01 14:24
One other annoyance is when you press the menu icon on screen XX and the window appears on screen YY 😢. I would also appreciate if the old menubar window can be re-added 👍

**Comment by AlexPattison** [comment] 2017-09-08 22:07
Looks like a duplicate of #298, but I would love to see this feature back.

**Comment by FezVrasta** [comment] 2017-09-27 12:25
This is waht the maintainer said about this feature:

> Tray Icon - On click show Gitify instead of menu
> I think that this makes sense in OSX for everyone that prefers the tray icon instead of the dock one. Me personally, I now use the dock icon only so it looks like it doesn't affect people using the dock icon. I will give it a go ASAP - I think it shouldn't take too long (working full time so will try my best time wise).

So I think it's an implicit "go ahead"?

**Comment by kaicataldo** [comment] 2017-09-27 15:00
@FezVrasta Mind linking to the source?

**Comment by FezVrasta** [comment] 2017-09-27 15:02
https://github.com/manosim/gitify/issues/298#issuecomment-309526669

**Comment by Tim15** [comment] 2017-10-29 12:43
Any updates on this? It seems there are plenty of people who want this feature.

**Comment by ericboehs** [comment] 2017-10-29 17:35
@Tim15 This doesn't solve the issue but helps a bit: https://github.com/manosim/gitify/pull/322. This pull request closes the window after you select a notification. I'm not sure if that fixes Spaces issues but it might.

**Comment by manosim** [comment] 2020-02-10 04:22
This feature is now back - actually Gitify v3 sticks back to the menu bar like v1 used to. See https://github.com/manosim/gitify/issues/298#issuecomment-583948207 Hope that makes everyone happy 😄

**Closed by manosim** 2020-02-10 04:22 UTC

**Comment by kaicataldo** [comment] 2020-02-10 15:33
Appreciate all the work you do!
